apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-akrom-id-tls
spec:
  secretName: k8s-id-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.akrom.id
  dnsName:
    - k8s.akrom.id
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.akrom.id